#!/usr/bin/env bash

export APP_CURTIS_BTC_ADMIN_PASSWORD="${APP_CURTIS_BTC_ADMIN_PASSWORD:-}"
export APP_CURTIS_BTC_POLL_SECONDS="${APP_CURTIS_BTC_POLL_SECONDS:-30}"
export APP_CURTIS_BTC_DISCORD_WEBHOOK="${APP_CURTIS_BTC_DISCORD_WEBHOOK:-}"
export APP_CURTIS_BTC_NOTIFY_BLOCKS="${APP_CURTIS_BTC_NOTIFY_BLOCKS:-true}"
export APP_CURTIS_BTC_NOTIFY_ATH="${APP_CURTIS_BTC_NOTIFY_ATH:-true}"
export APP_CURTIS_BTC_PRUNING_ENABLED="${APP_CURTIS_BTC_PRUNING_ENABLED:-false}"
export APP_CURTIS_BTC_PRUNING_TARGET_GB="${APP_CURTIS_BTC_PRUNING_TARGET_GB:-50}"
